#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use App\core\Command;

// ANSI colors
$colors = [
    'green' => "\033[32m",
    'yellow' => "\033[33m",
    'blue' => "\033[34m",
    'red' => "\033[31m",
    'reset' => "\033[0m"
];

// type "php flow ser"
$command = $argv[1] ?? null;

$cmd = new Command($colors);

switch ($command) {
    case 'ser':
        $host = 'localhost';
        $port = '2002';
        $entry = 'index.php';

        echo "{$colors['green']}🚀 Starting PHP server at {$colors['blue']}http://$host:$port{$colors['reset']}\n";
        echo "{$colors['yellow']}⏹ Press Ctrl+C to stop the server.{$colors['reset']}\n\n";

        // Detect OS to redirect stderr properly
        $isWindows = strtoupper(substr(PHP_OS, 0, 3)) === 'WIN';
        $redirect = $isWindows ? '2>nul' : '2>/dev/null';

        passthru("php -S $host:$port $entry $redirect");
        break;

    case (str_starts_with($command, 'make:controller') ? true : false):
        $className = $argv[2] ?? null;;
        $cmd->makeController($className);
        break;

    case (str_starts_with($command, 'make:model') ? true : false):
        $className = $argv[2] ?? null;
        $cmd->makeModel($className);
        break;

    case (str_starts_with($command, 'make:service') ? true : false):
        $className = $argv[2] ?? null;
        $cmd->makeService($className);
        break;

    case (str_starts_with($command, 'make:repository') ? true : false):
        $className = $argv[2] ?? null;
        $cmd->makeRepository($className);
        break;

    default:
        echo "{$colors['red']}❌ Unknown command: {$colors['reset']}$command\n";
        break;
}
